version: 2

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X github.com/AkashRajpurohit/git-sync/version.Version={{.Version}} -X github.com/AkashRajpurohit/git-sync/version.Build={{.Date}}
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    goarm:
      - 5
      - 6
      - 7
    ignore:
      - goos: darwin
        goarch: arm
      - goos: darwin
        goarch: arm64
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64
    hooks:
      post:
        # don't upx windows binaries as they make trouble with virus scanners
        - bash -c 'if [[ "{{ .Path }}" != *.exe ]] && [[ "{{ .Path }}" != *darwin* ]]; then upx {{ .Path }}; fi'

archives:
  - format: tar.gz
    name_template: >-
      {{ tolower .ProjectName }}_
      {{ tolower .RawVersion }}_
      {{ tolower .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ tolower .Arch }}{{ end }}
      {{- if .Arm }}v{{ tolower .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
release:
  prerelease: auto